// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFpCJBNJKwNVpqgVv2TmJEhJgKJtUIyAY',
    appId: '1:38356485980:web:6ae727b800e29d6e11a399',
    messagingSenderId: '38356485980',
    projectId: 'reci-6da55',
    authDomain: 'reci-6da55.firebaseapp.com',
    storageBucket: 'reci-6da55.appspot.com',
    measurementId: 'G-H2734Q3YLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvJSsNhjjH5CCLM9cB5TgnJs2dLqCUAJ0',
    appId: '1:38356485980:android:9854b44fdcf0e08f11a399',
    messagingSenderId: '38356485980',
    projectId: 'reci-6da55',
    storageBucket: 'reci-6da55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuTKU47hVB89s6QRnR44Ze0KoW3Kvp4KM',
    appId: '1:38356485980:ios:98be175adfb1bb2811a399',
    messagingSenderId: '38356485980',
    projectId: 'reci-6da55',
    storageBucket: 'reci-6da55.appspot.com',
    iosBundleId: 'com.example.reci',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuTKU47hVB89s6QRnR44Ze0KoW3Kvp4KM',
    appId: '1:38356485980:ios:98be175adfb1bb2811a399',
    messagingSenderId: '38356485980',
    projectId: 'reci-6da55',
    storageBucket: 'reci-6da55.appspot.com',
    iosBundleId: 'com.example.reci',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFpCJBNJKwNVpqgVv2TmJEhJgKJtUIyAY',
    appId: '1:38356485980:web:04ba239d0a752ea711a399',
    messagingSenderId: '38356485980',
    projectId: 'reci-6da55',
    authDomain: 'reci-6da55.firebaseapp.com',
    storageBucket: 'reci-6da55.appspot.com',
    measurementId: 'G-NF3N5KNM23',
  );
}
